services:
  tasks-api:
    image: node:alpine
    command: sh -c "npm i && npm run dev"
    working_dir: /usr/src/app
    volumes:
      - ./tasks-api:/usr/src/app
    ports:
      - 3333:3000
    env_file:
      - ./tasks-api/.env
    networks:
      - shrp
    depends_on:
      db:
        condition: service_started
      mq:
        condition: service_healthy

  ws:
    image: node:alpine
    command: sh -c "npm i && npm run dev"
    working_dir: /usr/src/app
    volumes:
      - ./ws:/usr/src/app
    ports:
      - 3080:3000
    env_file:
      - ./ws/.env
    depends_on:
      mq:
        condition: service_healthy
    networks:
      - shrp

  webclient:
    build: ./webclient
    ports:
      - 8181:80
    depends_on:
      - ws
    networks:
      - shrp

  db:
    image: mariadb
    env_file:
      - ./db/.env
    volumes:
      #- ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    networks:
      - shrp

  mq:
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./mq/.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ./mq/data/:/var/lib/rabbitmq/
      - ./mq/log/:/var/log/rabbitmq
    networks:
      - shrp

  adminer:
    image: adminer
    env_file:
      - ./adminer/.env
    ports:
      - 8080:8080
    networks:
      - shrp

networks:
  shrp:
    driver: bridge
