version: "3.9"

services:
  api:
    image: node:alpine
    command: sh -c "npm i && npm run dev:windows"
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3333:3000
    env_file:
      - .env
